### ISSUE TITLE
Add ---headless option to be passed to chrome/chromedriver

### ISSUE THREAD

**Issue by jd0323fhl** [Qarj/WebImblaze-Selenium#6]
Would it be possible to the option to webinject to in turn would allow Chrome to run headless.  I've tested selenium separately with the chrome driver and the "--headless" switch and it works well.  I would like to be able to run the test harness of webinject/selenium on a headless linux machine without Xvfb.  This would ultimately in my mind be another command line switch for Webinject

**Comment by Qarj** [comment]
@jd0323fhl I've not had any experience with this switch, but I guess it is feasible.

Perhaps setting up a Selenium Grid using Docker is a better approach? Take a look at this post at automation test guru: http://www.testautomationguru.com/selenium-grid-setup-using-docker/

It only takes 10 minutes to set up a Selenium Grid - including the Docker install and spin up a bunch of slaves. I set it up on Ubuntu and it worked fine.

The you just specify the --selenium-host and --selenium-port options to WebInject and it is effectively 'headless'.

Another approach - we run our automated tests using a non-interactive service account on a Windows Server (via Task Scheduler) - it is effectively headless.

'Headless' is a bit of a joke as concept as far as Selenium is concerned, you can just switch off your monitor for the same effect. The fact that you can take a screenshot and see the page proves that it really isn't headless. If you want to do a true headless test, do it all as http - which is what WebInject is great at.

**Comment by Qarj** [comment]
Ok, I've got this to work - as a hack you can change WebInject-Selenium.pm:

change the lines that read:
```perl
'extra_capabilities' => {'chromeOptions' => {'args' => ['window-size=1260,1568']}}
```

to read:
```perl
'extra_capabilities' => {'chromeOptions' => {'args' => ['--headless', 'window-size=1260,1568']}}
```

then it will always run it in headless mode. It is going to take a little more work to add that option to webinject.pl

You've actually solved a problem for me - now I know how to create screenshots bigger than the screen resolution - when you run in headless mode, the screen resolution is a limiting factor for the `window-size` 👍

**Comment by Qarj** [comment]
Ok, webinject.pl, WebInject-Selenium.pm and wif.pl have now been updated to support a `--headless` switch.

Keeping this open until the documentation is done.

**Comment by jd0323fhl** [comment]
Thanks.    We’re trying to make this run as part of a Splunk project using webinject and selenium and this should complete it.  Will update.

Thanks,

John

**Comment by Qarj** [comment]
Sure no problem, if you get stuck on something let me know. We've been using WebInject and Selenium together for years with a lot of success, but I'd like to tidy up the project more and give better examples on how to use it and all the features available, but just haven't had the time yet. Best of luck.

**Comment by Qarj** [comment]
This is working, but have stopped using it where I work since it seems flaky with - at least on Windows. Perhaps on a newer version of Chrome it will be better supported. When it works, it works really well.
